name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: compile Java sources
        run: |
          mkdir -p out
          find lib tests -name "*.java" > sources.txt
          javac -d out -cp lib:. @sources.txt

      - name: run Java tests
        run: |
          cd out
          for classfile in $(find . -name "*.class" | grep "^./tests/" | sed 's|./||' | sed 's|.class$||' | tr '/' '.'); do
            echo "Running $classfile..."
            java -cp . $classfile
          done
